# Generated by Django 3.2.8 on 2021-10-17 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=255, verbose_name='Nomres de Autores')),
                ('apellidos', models.CharField(max_length=255, verbose_name='Apellidos de Autores')),
                ('facebook', models.URLField(blank=True, null=True, verbose_name='Facebook')),
                ('twitter', models.URLField(blank=True, null=True, verbose_name='Instagram')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='Facebook')),
                ('web', models.URLField(blank=True, null=True, verbose_name='Wed')),
                ('correo', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('estado', models.BooleanField(default=True, verbose_name='Autor Activado/ No Activado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name': 'Autor',
                'verbose_name_plural': 'Autores',
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la categoría')),
                ('estado', models.BooleanField(default=True, verbose_name='Categoría Activada/Categoría no Activada')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorías',
            },
        ),
    ]
